baseURL = 'https://example.org/'
languageCode = 'fr-fr'
title = 'Kitkat Documentation'

[params]
    description = 'Centre de ressources pour les variateurs Danfoss'
    footer_text = 'MEDIA MESURES - Kitkat Documentation'
