baseURL = 'https://example.org/'
languageCode = 'fr-fr'
title = 'Centre de Ressources'
relativeURLs = true

[params]
    description = 'Documentations & Fiches Techniques Danfoss'
    footer_text = 'MEDIA MESURES'
